# Generated by Django 2.0.5 on 2018-05-03 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apartment', models.IntegerField(blank=True, null=True)),
                ('pg', models.IntegerField(blank=True, null=True)),
                ('room', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BHK',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('one', models.IntegerField(blank=True, null=True)),
                ('two', models.IntegerField(blank=True, null=True)),
                ('three', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=100)),
                ('addhar', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='ClientReivew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.IntegerField(blank=True, null=True)),
                ('comment', models.CharField(blank=True, max_length=200, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Furnish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fully', models.IntegerField(blank=True, null=True)),
                ('partially', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OwnerInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('mobile', models.DateField()),
                ('email', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=1000)),
                ('status', models.IntegerField(blank=True, default=1, null=True)),
                ('created_at', models.DateField(blank=True, null=True)),
                ('budget', models.IntegerField(blank=True, null=True)),
                ('family_preferrable', models.IntegerField(blank=True, null=True)),
                ('apartment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='search.Apartment')),
                ('bhk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='search.BHK')),
                ('furnish', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='search.Furnish')),
            ],
        ),
        migrations.AddField(
            model_name='ownerinfo',
            name='propertie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.Property'),
        ),
        migrations.AddField(
            model_name='clientreivew',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.OwnerInfo'),
        ),
    ]
