# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-12 08:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_property_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name=b'apartment',
        ),
        migrations.RemoveField(
            model_name='apartment',
            name=b'pg',
        ),
        migrations.RemoveField(
            model_name='apartment',
            name=b'room',
        ),
        migrations.RemoveField(
            model_name='bhk',
            name=b'one',
        ),
        migrations.RemoveField(
            model_name='bhk',
            name=b'three',
        ),
        migrations.RemoveField(
            model_name='bhk',
            name=b'two',
        ),
        migrations.AddField(
            model_name='apartment',
            name='name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='bhk',
            name='name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='furnish',
            name='fully',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='furnish',
            name='partially',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
