# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-12 10:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_auto_20180512_0820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='budget',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
