# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-13 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0005_auto_20180512_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownerinfo',
            name='password',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ownerinfo',
            name=b'email',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ownerinfo',
            name=b'mobile',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='ownerinfo',
            name=b'name',
            field=models.CharField(max_length=100),
        ),
    ]
