# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-13 16:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0006_auto_20180513_1644'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ownerinfo',
            old_name=b'mobile',
            new_name='owner_mobile',
        ),
        migrations.RenameField(
            model_name='ownerinfo',
            old_name='password',
            new_name='owner_password',
        ),
    ]
