# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-20 04:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0008_auto_20180513_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='lat',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='lng',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
