# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-20 06:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0009_auto_20180520_0444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='property',
            name='lng',
        ),
    ]
