# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-20 06:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0010_auto_20180520_0648'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
