# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-10 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0011_auto_20180520_0648'),
    ]

    operations = [
        migrations.AddField(
            model_name='furnish',
            name='unfurnished',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
