# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-13 17:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0012_furnish_unfurnished'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family', models.IntegerField(blank=True, default=0, null=True)),
                ('girls', models.IntegerField(blank=True, default=0, null=True)),
                ('bachelor', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='ownerinfo',
            name=b'propertie',
        ),
        migrations.RemoveField(
            model_name='property',
            name=b'family_preferrable',
        ),
        migrations.AddField(
            model_name='property',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='search.OwnerInfo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='preference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='search.Preference'),
        ),
    ]
